create table book
(
    id         bigint generated by default as identity
        primary key,
    age_rating integer,
    author     varchar(255),
    title      varchar(255)
);

alter table book
    owner to postgres;

create table book_copy
(
    id      bigint generated by default as identity
        primary key,
    book_id bigint
        constraint fkpqftp65hd66ae8wsx7pp2cxcs
            references book
);

alter table book_copy
    owner to postgres;

create table loan_type
(
    id            bigint generated by default as identity
        primary key,
    max_loan_days integer,
    name          varchar(255)
);

alter table loan_type
    owner to postgres;

create table subscription_type
(
    id                 bigint generated by default as identity
        primary key,
    max_loan_days      integer,
    name               varchar(255),
    penalty_days       integer,
    quota_extends      integer,
    quota_loans        integer,
    quota_reservations integer
);

alter table subscription_type
    owner to postgres;

create table member
(
    id                      bigint generated by default as identity
        primary key,
    address                 varchar(255),
    birth_date              date,
    email                   varchar(255),
    extend_count            integer,
    first_name              varchar(255),
    is_admin                boolean not null,
    last_name               varchar(255),
    password                varchar(255)

);

alter table member
    owner to postgres;

create table subscription
(
    id                 bigint generated by default as identity primary key,
    member_id          bigint
        constraint fkq6x5j1k2c3h4g5f6g7h8i9j0k1
            references member,
    penalty_end_date        date,
    subscription_end_date   date,
    subscription_start_date date,
    subscription_type_id    bigint
        constraint fkhtq7nbhsicuisfsya68tx7iu0
            references subscription_type
);

alter table subscription
    owner to postgres;

create table loan
(
    id                 bigint generated by default as identity
        primary key,
    end_date           date,
    is_returned        boolean not null,
    prevision_end_date date,
    start_date         date,
    book_copy_id       bigint
        constraint fkhq4lfr6shkjcbqvn0if6sqtwf
            references book_copy,
    loan_type_id       bigint
        constraint fkkx2hqvulcu3hai1h3yakvmnfm
            references loan_type,
    member_id          bigint
        constraint fkskvlv9lnj3plivn0grmqf950f
            references member
);

alter table loan
    owner to postgres;

create table reservation
(
    id               bigint generated by default as identity
        primary key,
    is_approved      boolean not null,
    reservation_date date,
    book_copy_id     bigint
        constraint fkp19371ju01sg0c1dv354jjmxd
            references book_copy,
    loan_type_id     bigint
        constraint fk9awrcrtp7qn9kwnj34a2g2tk6
            references loan_type,
    member_id        bigint
        constraint fk68999qe28ym9eqqlowybh9nvn
            references member
);

alter table reservation
    owner to postgres;

create table holiday
(
    id         bigint generated by default as identity
        primary key,
    local_date date
);

alter table holiday
    owner to postgres;

